version: 2
jobs:
  build:
    docker:
      - image: centos:latest
    steps:
      - run:
        command: |
          yum install -y epel-release
          yum -y install git mongodb mongodb-server python-pip
          pip install --upgrade pip
          pip install futures pymongo tornado pyjwt ldap3
          git clone https://github.com/WIPACrepo/file_catalog
          cd file_catalog
          python -m unittest discover
